# replace the placeholders with real login values
# rename the file to be just: config.yml
lighthouse:
  account: ACCOUNT_NAME
  username: USERNAME 
  password: PASSWORD

google:
  account: HOSTED_OR_GOOGLE
  email: EMAIL 
  password: PASSWORD
  service: wise
